version: "2"

services: 
  domain1221:
    image: greggu/weblogic-base:0.1-dev
    container_name: wlsadmin
    build: 
      context: ./1221-domain
      dockerfile: Dockerfile
      args: 
        - "ADMIN_PASSWORD=welcome1"
        - "DOM_PRODUCTION_MODE=dev"
    ports: 
      - "7001:7001"
