FROM greggu/weblogic-base:0.1-prod

# Define variables
ENV APP_NAME="account" \
    APP_PKG_FILE="account.war" \
    APP_PKG_LOCATION="/u01/oracle"

# Copy files and deploy application in WLST Offline mode
COPY deploy/* /u01/oracle/

RUN wlst /u01/oracle/app-deploy.py
